### ISSUE TITLE
能否将微信先从后台拉起到前台，然后打开聊天窗口

### ISSUE THREAD

**Issue by antergone** [TKkk-iOSer/wechat-alfred-workflow#1]
首先 感谢作者的开源。

我们在输入 `wx {nickname} ` command+enter 的时候能否先将微信窗口从dock唤醒然后切换到最前方并且打开对应的聊天窗口。

想法有点过分。。 不知道能不能实现。

**Comment by TKkk-iOSer** [comment]
之后再调研看看

**Comment by xiaochunjimmy** [comment]
我也是发现，当微信窗口没有在前台展示的时候，使用workflow调用微信没办法做到直接唤起，还是得手动点击一下dock图标，但是点击后发现其实已经切换到在Workflow里输入的昵称的对话界面了

**Comment by cityO** [comment]
我 也出现了这种情况

**Comment by lzane** [comment]
可以使用下面方法解决：

- 在alfred workflow的设置界面里面右键
- 添加一个Actions - launch app, 选择微信
- 把线连好

![image](https://user-images.githubusercontent.com/12814398/38315586-5d5b33d2-385b-11e8-9163-a3840dc2b5c6.png)

**Comment by TKkk-iOSer** [comment]
@lzane goodJob, 之后加上.👍

**Comment by antergone** [comment]
@lzane 妥了！！  66666

**Comment by kuankuanlv** [comment]
@lzane 可以说非常厉害了前辈

**Comment by TKkk-iOSer** [comment]
根据 @lzane 的建议，fixed

**Comment by lzane** [comment]
@TKkk-iOSer 辛苦作者。
