### ISSUE TITLE
提示『请确保登录微信』

### ISSUE THREAD

**Issue by quanru** [TKkk-iOSer/wechat-alfred-workflow#10]
![image](https://user-images.githubusercontent.com/11739753/40882437-6691070a-6714-11e8-90e2-fbaa38f4603b.png)
![image](https://user-images.githubusercontent.com/11739753/40882439-8389cb8a-6714-11e8-8b4c-a5ba595af687.png)

已经确保了的

**Comment by TKkk-iOSer** [comment]
是否有登录多个微信账号？比如说先登录一个微信账号之后在登录另一个，然后退出第一个微信账号，那么这样会失效。
另一个就是有可能端口被占用了…

**Comment by quanru** [comment]
就登录了一个微信，哪个端口？
