### ISSUE TITLE
亲，搜不到群

### ISSUE THREAD

**Issue by davymai** [TKkk-iOSer/wechat-alfred-workflow#13]
亲，搜不到群
[截图](https://xmyunwei.com/wx20180608-2034092x)
设备类型：MacBookPro14,3
系统版本：版本 10.13.5（版号 17F77）
系统语言：zh-Hans
微信版本：Version. 2.3.14 (11004)  v2.3.14.16 (0x12030e10) #5bf142180
微信语言：zh-Hans
历史版本：[2018-05-10 23:11:28.195] Version. 2.3.13 (10763)  v2.3.13.16 (0x12030d10) #7fdf48a29
网络状态：Reachable via WiFi
显  示  器：*(1680x1050)/Retina

**Comment by hgt803** [comment]
+1

**Comment by greatoe** [comment]
+1

**Comment by TKkk-iOSer** [comment]
应该是微信更新了，接口失效了，我的是Version. 2.3.113，目前是可以

**Comment by hgt803** [comment]
我的是Version2.3.15

**Comment by greatoe** [comment]
微信 v2.3.15(11012)，搜不到群

**Comment by heureuxchaquejour** [comment]
+1， Version. 2.3.16 (11023) 同样搜不到群。

**Comment by Apecice** [comment]
+1 wx Version. 2.3.15 (11012)

**Comment by vincent66666** [comment]
我也收不到群

**Comment by TKkk-iOSer** [comment]
已修复，另新增搜索最近聊天，输入wx (2个空格)即可

**Comment by wangxiexe** [comment]
+1   

wx version : Version 2.3.17 (11255)
assistant : 1.7.1

2个空格可以看到最近群聊天记录，但输入群名还是搜索不到

**Comment by TKkk-iOSer** [comment]
你们用微信官方的搜索能搜到群么？另外是否都更新了小助手跟workflow？
![image](https://user-images.githubusercontent.com/11961989/43372943-d1363026-93d8-11e8-9de0-0d57bb0e58e2.png)

**Comment by leyle** [comment]
用官方搜索可以搜索到群，插件和 workflow 都更新到最新的了，还是无法搜索群。

**Comment by TKkk-iOSer** [comment]
你们的群有在最近聊天列表么？刚刚更新了，优化了一些逻辑，可以更新下小助手跟workflow。

**Comment by leyle** [comment]
插件和这个 workflow 我都更新了，然后只要在 Alfred 中一输入 wx 就会导致 微信崩溃。

**Comment by TKkk-iOSer** [comment]
@leyle 方便提供一下微信号么？发这里或者发我邮箱都可以，我联系你然后调试下。

**Comment by leyle** [comment]
@TKkk-iOSer  已经发给你邮箱了，你查收一下。

**Comment by TKkk-iOSer** [comment]
Fixed
