### ISSUE TITLE
通过workflow打开聊天窗口部分场景失败

### ISSUE THREAD

**Issue by tiany** [TKkk-iOSer/wechat-alfred-workflow#14]
对正常的微信聊天窗口进行 `command + H / 最小化 / 关闭(窗口左上角关闭按钮)` 操作后，然后通过workflow的 `wx 用户名` + `command + enter` 来打开对应的聊天窗口，发现只有 `command + H` 隐藏的窗口可以被唤起，而 `最小化` 和 `关闭` 的则都不可以。

微信版本：`2.3.15 (11012)`
WeChat Assistant版本：`1.7`
MacOS: `10.13.5`

**Comment by TKkk-iOSer** [comment]
把微信 & 小助手 & workflow 都更新试试。

**Comment by tiany** [comment]
新版本测试OK，但是微信更新了，新版本会Crash =。=，我先关掉这个issue…
