### ISSUE TITLE
使用wx 然后微信崩溃

### ISSUE THREAD

**Issue by skyblue4cn** [TKkk-iOSer/wechat-alfred-workflow#15]
最新版使用alfred插件有毒，会导致微信崩溃...

**Comment by zhanpenng** [comment]
微信崩溃+1

**Comment by ethanfun** [comment]
崩溃 +1

**Comment by soberzhou** [comment]
崩溃 +1

**Comment by Ninzero** [comment]
崩溃+1

**Comment by doocii** [comment]
崩溃+1

**Comment by yangwenmai** [comment]
崩溃+1

**Comment by TKkk-iOSer** [comment]
已修复，另新增搜索最近聊天，输入`wx (2个空格)`即可

**Comment by sysuxw** [comment]
真巧，我在你修复前10分钟clone的。。

**Comment by yangwenmai** [comment]
@TKkk-iOSer 现在还没有更新到GitHub？

**Comment by TKkk-iOSer** [comment]
@yangwenmai 更新了，重装`WeChatPlugin-MacOS`就行了

**Comment by yangwenmai** [comment]
我重新安装 [WeChatPlugin-MacOS](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS) ，`curl -o- -L https://raw.githubusercontent.com/lmk123/oh-my-wechat/master/install.sh | bash -s`，但是还是输入wx xxx 就闪退了。

**Comment by yangwenmai** [comment]
使用 `cd ~/Downloads && rm -rf WeChatPlugin-MacOS && git clone https://github.com/TKkk-iOSer/WeChatPlugin-MacOS.git --depth=1 && ./WeChatPlugin-MacOS/Other/Install.sh` 安装的是可以使用的。

**Comment by TKkk-iOSer** [comment]
@yangwenmai 可能使用 owm 安装的话用的是本地的缓存，导致不是最新的。

**Comment by snowleopardw** [comment]
搜到人后，按 回车 输入内容就会闪退，按 command + 回车可以正常聊天。

**Comment by TKkk-iOSer** [comment]
@snowleopardw 增加了限制，重新安装试试

**Comment by zhongdom** [comment]
按照上面的方法删除项目重新clone安装，输入 `wx + 2个空格` 微信就崩溃了

**Comment by TKkk-iOSer** [comment]
@zhongdom 提供下微信的版本，另外请确定下是clone了今天最新版本，早上有更新了。还有就是要更新workflow。

**Comment by zhongdom** [comment]
@TKkk-iOSer  都是最新的了
### workflow版本
```
commit d7106d82e33f1c7448e673575560e0ff58b180bd (HEAD -> master, origin/master, origin/HEAD)
Author: tk <1049893361@qq.com>
Date:   Tue Jul 24 23:42:34 2018 +0800

    Update ==> README.md
```

### 插件版本
```
commit 662c58995a4d6f796ef868cfb3e609d7e6060f97 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: tk <1049893361@qq.com>
Date:   Wed Jul 25 09:00:16 2018 +0800

    Update ==> 完善 alfred 聊天记录展示
(END)
```

**Comment by TKkk-iOSer** [comment]
@zhongdom 微信版本呢，建议重新装下

**Comment by zhongdom** [comment]
@TKkk-iOSer  微信从AppStore安装的，卸载重新安装就不会崩溃了
