### ISSUE TITLE
alfred 搜索好友，json解析报错

### ISSUE THREAD

**Issue by Louiszhai** [TKkk-iOSer/wechat-alfred-workflow#16]
[WARNING: input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 68.)'. Row 1, Col 7: 'error parsing attribute name' in XML:
<type 'exceptions.IOError'>
![image](https://user-images.githubusercontent.com/8412301/43630065-bf8109b2-9731-11e8-9850-0e14f9a72336.png)

**Comment by TKkk-iOSer** [comment]
重新下载安装小助手跟workflow试试，刚更新了

**Comment by Louiszhai** [comment]
后面发现是网络代理的问题，已解决，谢谢
