### ISSUE TITLE
Alfred 3.6.2 执行 wx 命令报错

### ISSUE THREAD

**Issue by GoingAI** [TKkk-iOSer/wechat-alfred-workflow#18]
![image](https://user-images.githubusercontent.com/9779970/44070436-71093d26-9fb6-11e8-8b17-a23e1df6cdda.png)

**Comment by TKkk-iOSer** [comment]
修复了，重新安装小助手跟wechat-alfred-workflow

**Comment by W-quan** [comment]
@TKkk-iOSer Sure?  我刚安装的，也是这样

**Comment by W-quan** [comment]
```
Starting debug for 'WeChat Plugin'

[2018-08-21 10:16:32][ERROR: input.scriptfilter] Code 1: .
10:16:31 workflow.py:2055 DEBUG    ---------- WeChat Plugin (1.0.0) ----------
10:16:31 workflow.py:2074 ERROR    'copyText'
Traceback (most recent call last):
  File "/Users/wzq/Applications/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.7B249CB3-7DDD-43E5-B43C-EAE7B2878784/workflow/workflow.py", line 2067, in run
    func(self)
  File "search.py", line 23, in main
    copyText = item['copyText']
KeyError: 'copyText'
10:16:31 workflow.py:2097 DEBUG    ---------- finished in 0.017s ----------
```

版本怎么还是1.0 ?  我是下载master最新的

**Comment by qbosen** [comment]
一样的问题。
从时间上来看，`workflow`这边并没有更新。从`release`下载的和从`master`直接下载的均显示`1.0.0`版本。

**Comment by TKkk-iOSer** [comment]
`workflow` 跟 `小助手`都直接 `git clone` 下载，`小助手`再用`Install.sh`安装，有些只是小修改没有进行打包。之前联系了一个人，也是报错，后来发现使用owm的话没有更新，可能的原因是我没有打tag，所以下载下来不是最新的。(另外alfred上面的版本忘了改了，所以还是显示1.0

**Comment by dreistein543** [comment]
小助手和workflow以及Alfred均为目前最新版本，实测结果是输入`wx`(不带空格)可以看见最近聊天列表，可以进行下一步操作（如选定聊天对象，回复信息等）；
输入`wx `(带一个空格)稳定，输入`wx [任意字符]`(带一个空格+任意字符)闪退

**Comment by GoingAI** [comment]
我这边更新了版本后一切正常
