### ISSUE TITLE
多开微信下alfred操作能否同时兼容两个微信账号？

### ISSUE THREAD

**Issue by charlieshen7** [TKkk-iOSer/wechat-alfred-workflow#2]
同时开两个微信的情况下（假定为账号1和账号2）
alfred的插件似乎只能搜索到一个账号下的联系人信息（假定可搜索的到的为账号1）
将账号1退出后，alfred依然不能搜索到账号2的联系人信息

不知道是否可以在alfred插件中同时搜索到多个账号下的联系人信息吗~

**Comment by TKkk-iOSer** [comment]
* 多账号的话可能存在一个问题。假设账号 `A` 跟账号 `B` 有共同好友 `C` ，这时候你想通过 `A` 去给 `C` 发送消息，如果都同时显示出来的话，那么可能会导致变成 `B` 给 `C` 发送消息。
* 另外账号1退出后，alfred 搜索不到账号2的原因是因为开启这个服务是在微信一启动就开启的，如果检测到账号1已开启，账号2就无法开启，因为端口号被占了。

**Comment by charlieshen7** [comment]
这样，明白了
感谢大佬开发这个插件~
