### ISSUE TITLE
微信2.3.19版本搜索无效

### ISSUE THREAD

**Issue by Fanchao-Qi** [TKkk-iOSer/wechat-alfred-workflow#26]
微信版本：2.3.19
小助手版本：1.7.3
wordflow版本：2.0

问题：在alfred输入框输入wx+关键词后，显示的搜索结果和关键词无关，只是按照微信的聊天框的顺序显示结果。

**Comment by hexid26** [comment]
wechat 又偷偷更新了，难受。。。

**Comment by TKkk-iOSer** [comment]
Fixed
