### ISSUE TITLE
搜索不到好友

### ISSUE THREAD

**Issue by beijiahiddink** [TKkk-iOSer/wechat-alfred-workflow#3]
搜索好友那里一直搜索中，微信版本2.3.11

**Comment by TKkk-iOSer** [comment]
ok，请求问2.3.11还有其他问题么

**Comment by beijiahiddink** [comment]
现在卡在搜索那里了，其他问题也发现不了

**Comment by TKkk-iOSer** [comment]
我指的是小助手的其他功能，类似自动回复之类的

**Comment by beijiahiddink** [comment]
微信退出偶尔会有卡死问题，我没装网易云音乐，执行休眠等指令会弹出让我选择网易云音乐的弹窗

**Comment by TKkk-iOSer** [comment]
升级到了2.3.11，我倒是不会，无论是卡死还是说执行指令异常… mac版本是多少？

**Comment by beijiahiddink** [comment]
10.13.3

**Comment by bbxytl** [comment]
无法使用，输入 wx 后，一直显示 "搜索中..." 其他没反应。
mac 版本：10.11.6
微信版本：2.3.11

**Comment by bbxytl** [comment]
在 search.py 里加如了 print， 看了下 baseUrl 的值为 None

$ python search.py "test"
.
None test
16:43:00 workflow.py:2074 ERROR    unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File ".../AppData/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A55162C7-21BB-4C8F-A012-2A78640103A3/workflow/workflow.py", line 2067, in run
    func(self)
  File "search.py", line 13, in main
    url = baseUrl + 'user?keyword=' + query
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by TKkk-iOSer** [comment]
不确定是不是python版本的原因。@bbxytl 可以先把 `baseUrl`全都替换成 `http://127.0.0.1:52700/wechat-plugin/`，这个是全局变量

**Comment by TKkk-iOSer** [comment]
@beijiahiddink 重新装下小助手跟这个workflow试试

**Comment by nullptrx** [comment]
遇到类似的问题，换了个端口就可以了。先前的端口请求一直没有响应。
