### ISSUE TITLE
无法显示头像

### ISSUE THREAD

**Issue by selfmaking** [TKkk-iOSer/wechat-alfred-workflow#35]
![image](https://user-images.githubusercontent.com/21097577/50261826-451a8380-0449-11e9-9b01-981d744a755f.png)

这是怎么回事呢

**Comment by liguidong** [comment]
![image](https://user-images.githubusercontent.com/17565771/50319698-95561c00-0503-11e9-99d6-dd4ea88b65ad.png)
一样的情况

**Comment by bingbingbog** [comment]
看看这个bug呗兄弟

**Comment by Issacwww** [comment]
也是这样的情况，有解决方案嘛～
![image](https://user-images.githubusercontent.com/15892569/52595586-37b3c100-2e1c-11e9-9178-dcebab01bb0d.png)

**Comment by TKkk-iOSer** [comment]
浏览器输入 http://127.0.0.1:52700/wechat-plugin/user?keyword= ，然后看下 icon 字段在 Finder 里面找得到么 @Issacwww

**Comment by Issacwww** [comment]
@TKkk-iOSer 
"icon":"\/Users\/ssuchao\/Library\/Containers\/com.tencent.xinWeChat\/Data\/Library\/Caches\/com.tencent.xinWeChat\/2.0b4.0.9\/8f3d1a95b751a5e934202253904c57ec\/avatar\/6d72aece5f15dddb7ef7a6ecd0ee82d0"
没有avatar目录

**Comment by TKkk-iOSer** [comment]
@Issacwww 谢谢，知道原因了，过几天修复下

**Comment by TKkk-iOSer** [comment]
已修复，请更新小助手到最新 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/archive/master.zip

**Comment by Issacwww** [comment]
@TKkk-iOSer 还有一点点小问题，我有一个群聊置顶了，图标就是微信logo，取消置顶之后也没有变化，测试了其他未置顶的群，置顶之后图标也变成logo，取消置顶后也无变化，去看了之前给的http://127.0.0.1:52700/wechat-plugin/user?keyword=
地址，icon字段置顶的群组的值都是空的，该bug只出现在群聊，测试了私聊个人用户没有问题
