### ISSUE TITLE
插件导致wechat crash

### ISSUE THREAD

**Issue by sevck** [TKkk-iOSer/wechat-alfred-workflow#38]
第一次运行时会将微信小助手更新到最新版本。
正在检查新版本……
发现新版本 v1.7.3。
开始下载微信小助手 v1.7.3……
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134    0   134    0     0    123      0 --:--:--  0:00:01 --:--:--   124
100 13.2M    0 13.2M    0     0  33510      0 --:--:--  0:06:54 --:--:-- 37415^[[C
下载完成
开始安装微信小助手……

为了将小助手写入微信, 请输入密码 ：
Password:
Sorry, try again.
Password:
/Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
微信小助手安装完成。
打开微信
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/WeChat.app.

**Comment by TKkk-iOSer** [comment]
更新wechatplugin到最新
