### ISSUE TITLE
请问能否增加对公众号和服务号的支持

### ISSUE THREAD

**Issue by imkaihao** [TKkk-iOSer/wechat-alfred-workflow#4]
感谢作者提供了这么强大的插件，不过个人有些需求需要结合公众号或服务号，比如发送微信文章的链接到“我的印象笔记”来保存、发送“余额”到“中国工商银行电子银行”来查看余额等等。

希望能够增加对公众号和服务号的支持。

**Comment by TKkk-iOSer** [comment]
想法是不错，但是限制比较大，因为各个公众号的都不一样

**Comment by imkaihao** [comment]
@TKkk-iOSer 不太清楚各个公众号是什么不一样？我不是要求对特定公众号开发特定的功能，只要能够像目前“好友”一样实现快速搜索、快捷发送消息、快捷打开聊天窗口这几个功能就可以了。

**Comment by TKkk-iOSer** [comment]
我大概懂你的意思了，你的意思就是说支持公众号的搜索 & 快速发送消息给公众号是吧。

**Comment by imkaihao** [comment]
对的

**Comment by TKkk-iOSer** [comment]
已加
