### ISSUE TITLE
微信 2.3.24 (12222) ，wx 提示“确保安装小助手”。

### ISSUE THREAD

**Issue by aetherwu** [TKkk-iOSer/wechat-alfred-workflow#42]
- 小助手版本 1.7.5，懒人安装
- 微信版本 2.3.24 (12222)
- Alfredworkflow WeChat Plugin 版本 https://github.com/TKkk-iOSer/wechat-alfred-workflow/blob/master/WeChat%20Plugin.alfredworkflow

操作：
- 从命令行启动

> $ omw
> [13:03:42] 当前没有安装微信小助手
> [13:03:42] 正在查询新版本……
> [13:03:43] 微信小助手的最新版本为 v1.7.5
> [13:03:43] 开始安装微信小助手……
> /Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
> LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
> Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
> [13:03:43] 微信小助手安装完成。
> [13:03:43] 打开微信

- 顶部菜单栏可以看到小助手
- 已从折叠菜单中启用小助手
- Alfredworkflow 输入 wx，提示“请确保已安装....”

Workflow debug 错误提示：

Starting debug for 'WeChat Plugin'

> [2019-03-28 13:07:29][STDERR: input.scriptfilter] .
> 13:07:28 workflow.py:2055 DEBUG    ---------- WeChat Plugin (2.0.0) ----------
> 13:07:29 workflow.py:1462 DEBUG    reading settings from /Users/Aether/Library/Application Support/Alfred 3/Workflow Data/tkkk.wechatPlugin/settings.json
> 13:07:29 workflow.py:2248 DEBUG    set last run version: 2.0.0
> 13:07:29 workflow.py:2097 DEBUG    ---------- finished in 0.286s ----------
> [2019-03-28 13:07:31][STDERR: input.scriptfilter] .
> 
> 13:07:31 workflow.py:2055 DEBUG    ---------- WeChat Plugin (2.0.0) ----------
> 13:07:31 workflow.py:1462 DEBUG    reading settings from /Users/Aether/Library/Application Support/Alfred 3/Workflow Data/tkkk.wechatPlugin/settings.json
> 13:07:31 workflow.py:2248 DEBUG    set last run version: 2.0.0
> 13:07:31 workflow.py:2097 DEBUG    ---------- finished in 0.285s ----------

看源代码是 IOError 错误，具体没细看，想先报到这里。

其他
和 os env 有关系吗？我这里 echo $baseUrl 是空值。

**Comment by aetherwu** [comment]
忽然它自己又可以用了……（捂脸）。
一脸萌呆。

**Comment by ikingye** [comment]
Wechat Assistant -> enable alfred
