### ISSUE TITLE
这个现在是不是已经用不了了

### ISSUE THREAD

**Issue by Anonym-w** [TKkk-iOSer/wechat-alfred-workflow#58]

**Comment by zyzweb1** [comment]
还能用吗

**Comment by Lucciv** [comment]
好久没再用了


| |
杜赫
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年01月11日 10:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | Re: [TKkk-iOSer/wechat-alfred-workflow] 这个现在是不是已经用不了了 (Issue #58) |

还能用吗

**Comment by zyzweb** [comment]
1

**Comment by zyzweb** [comment]
> commented
现在有推荐的吗

**Comment by TKkk-iOSer** [comment]
可以用了
