### ISSUE TITLE
搜索不到任务内容

### ISSUE THREAD

**Issue by iblogc** [TKkk-iOSer/wechat-alfred-workflow#7]
微信版本：Version. 2.3.11 (10370)
微信小助手版本：v1.6.1 (2018-04-06)

![image](https://user-images.githubusercontent.com/3283023/38464302-0201905e-3b3e-11e8-805a-e9a940a96b48.png)

**Comment by TKkk-iOSer** [comment]
我的没问题，刚更新了2.3.11，小助手确保安装成功了么？是否重启微信？

**Comment by iblogc** [comment]
@TKkk-iOSer 小助手是双击那个`.alfredworkflow`安装就可以了吧，微信也重启过，系统也重启过。

**Comment by TKkk-iOSer** [comment]
小助手是这个 [WeChatPlugin-MacOS](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS)

**Comment by iblogc** [comment]
@TKkk-iOSer 说错了，这个插件（wechat-alfred-workflow）是点击`.alfredworkflow`后缀文件安排的，小助手（WeChatPlugin-MacOS）也是安装了的，自动回复防撤回这些都能用。

**Comment by iblogc** [comment]
今天试了下又可以用了
